version: 2

builds:
  - main: ./cmd/agrev
    binary: agrev
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/aezell/agrev/internal/cli.version={{.Version}}
      - -X github.com/aezell/agrev/internal/cli.commit={{.Commit}}
      - -X github.com/aezell/agrev/internal/cli.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
