package cli

import (
	"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
	Use:   "agrev",
	Short: "Agent Review — code review tool for AI-generated changes",
	Long: `agrev is an opinionated code review tool for changes generated by AI coding agents.
It combines diff review with agent trace analysis, static analysis, and interactive
review actions to help you understand, assess, and selectively approve changes.`,
}

func Execute() error {
	return rootCmd.Execute()
}

func init() {
	rootCmd.AddCommand(reviewCmd)
	rootCmd.AddCommand(summaryCmd)
	rootCmd.AddCommand(checkCmd)
	rootCmd.AddCommand(versionCmd)
}
